apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sdenyallgateway
spec:
  crd:
    spec:
      names:
        kind: K8sDenyAllGateway
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sdenyallgateway

        operations = {"CREATE", "UPDATE"}

        identical(obj, review) {
          obj.metadata.namespace == review.object.metadata.namespace
          obj.metadata.name == review.object.metadata.name
        }

        contains(other, hosts) {
          s2 := other.spec.servers[_].hosts[_] == hosts[_]
        }
        
        violation[{"msg": msg}] {
          input.review.kind.kind == "Gateway"
          operations[input.review.operation]
          re_match("^(networking.istio.io)$", input.review.kind.group)

          hosts := input.review.object.spec.servers[_].hosts
          other := data.inventory.namespace[ns][apiversion]["Gateway"][resourcename]
          not identical(other, input.review)
          not contains(other, hosts)
          msg := sprintf("REVIEW OBJECT: %v", [[input.review.uid,ns,resourcename, hosts]])
        }

---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDenyAllGateway
metadata:
  name: deny-all-gateways
spec:
  match:
    kinds:
      - apiGroups: ["networking.istio.io"]
        kinds: ["Gateway"]
